### ISSUE TITLE
[PE-D][Tester A] 2 People can share the same number 

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-W09-3/tp#118]
![image.png](https://raw.githubusercontent.com/RunjiaChen/ped/main/files/b633db9d-e9ab-4f3b-89b4-30fee3077627.png)
2 People with different name can share the same number, which may be invalid

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: RunjiaChen/ped#14

**Comment by zhuuyicheng** [comment]
Two people can have:

- same number if they work at the same company so same company number
- same address if they live at the same place/company address
- same email if it's a company email
