### ISSUE TITLE
[PE-D][Tester D] Archiving a person does not affect their reservations

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-W09-3/tp#75]
Pretty inconvenient to have to manually remove all a person's reservations one by one if they are archived

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: nichee/ped#4

**Comment by ziiqii** [comment]
Todo: Update documentation in UG to make it clearer to users that archive has no relation to reservation.
